language: objective-c

branches:
 only:
 - master

xcode_project: ITHelpApp-iOS.xcworkspace
xcode_scheme: ITHelpApp-iOSTests
osx_image: xcode7
xcode_sdk: iphonesimulator9.0

script:
- xcodebuild clean build test -project ITHelpApp-iOS.xcworkspace -scheme ITHelpApp-iOSTests
