# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ITHelpApp-iOS' do
  pod 'Parse'

  source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!
  pod "PubNub", "~> 4.0"
end

target 'ITHelpApp-iOSTests' do

end

target 'ITHelpApp-iOSUITests' do

end
