# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target 'ITHelpApp-iOS' do
	pod 'Parse'
end

target 'ITHelpApp-iOSTests' do

end

target 'ITHelpApp-iOSUITests' do

end
