language: objective-c

branches:
 only:
 - master

xcode_project: ITHelpApp-iOS.xcodeproj
xcode_scheme: ITHelpApp-iOSTests
osx_image: xcode7.0.1
xcode_sdk: iphonesimulator9.0

script:
- xcodebuild clean build test -project ITHelpApp-iOS.xcodeproj -scheme ITHelpApp-iOSTests
