language: objective-c

branches:
 only:
 - master

xcode_project: Swifternalization.xcodeproj
xcode_scheme: SwifternalizationTests
osx_image: beta-xcode7.0.1
xcode_sdk: iphonesimulator9.0

script:
- xcodebuild clean build test -project ITHelpApp-iOS.xcodeproj -scheme ITHelpApp-iOSTests
